/*****************************************************************************
  FILE           : $Source: /projects/higgs1/SNNS/CVS/SNNS/kernel/sources/kr_amap.h,v $
  SHORTNAME      : 
  SNNS VERSION   : 4.2

  PURPOSE        : SNNS Kernel Function Prototypes for ARTMAP-Networks
  NOTES          :

  AUTHOR         : Kai-Uwe Herrmann
  DATE           : 17.05.92

  CHANGED BY     : Sven Doering
  RCS VERSION    : $Revision: 2.6 $
  LAST CHANGE    : $Date: 1998/02/25 15:26:28 $

    Copyright (c) 1990-1995  SNNS Group, IPVR, Univ. Stuttgart, FRG
    Copyright (c) 1996-1998  SNNS Group, WSI, Univ. Tuebingen, FRG

******************************************************************************/
#ifndef _KR_AMAP_DEFINED_
#define  _KR_AMAP_DEFINED_




extern int             ArtMap_NoOfInpUnits_a;
extern int             ArtMap_NoOfInpUnits_b;
extern int             ArtMap_NoOfRecUnits_a;
extern int             ArtMap_NoOfRecUnits_b;

extern struct Unit    *ArtMap_cl_unit;  /* Pointer to cl-unit */
extern struct Unit    *ArtMap_nc_unit;  /* Pointer to nc-unit */




/***************************************************************************/
/* kram_init_i_act ()

   Sets the initial activation values of the units
*/
 krui_err kram_init_i_act (

                                 double rho_a,
                                 double rho_b,
                                 double rho

                                );


/***************************************************************************/
/* kram_sort ()

   Check for ARTMAP topology and create topo ptr array
*/
 krui_err  kram_sort (

                            void

                           );




/***************************************************************************/
/* kram_getClassNo ()

   Returns the number of the actually activated class K, 1 <= K <= Mb
*/
 int  kram_getClassNo (

                             void

                            );



/***************************************************************************/
/* kram_AllMapUnitsActive ()

   Returns TRUE, if all MAP-Field-Units are active, else, FALSE
*/
 bool  kram_AllMapUnitsActive (

                                     void

                                    );




#endif 

/* 94 lines generated by deleteprivatedefinitions.awk */
